# Tearing for games
allow_tearing=1

border_radius=6

# laptop at the bottom
monitorrule=name:eDP-1,scale:1,x:384,y:2160
# Dell on top
monitorrule=name:DP-6,scale:1,x:0,y:0

# shows all workspaces
tagrule=id:1,no_hide:1
tagrule=id:2,no_hide:1
tagrule=id:3,no_hide:1
tagrule=id:4,no_hide:1
tagrule=id:5,no_hide:1
tagrule=id:6,no_hide:1
tagrule=id:7,no_hide:1
tagrule=id:8,no_hide:1
tagrule=id:9,no_hide:1

# rofi binds
bind=SUPER,Space,spawn,rofi -show drun

# workspace binds
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# Vim-style window navigation with Super key
bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=SUPER,l,focusdir,right


bind=SUPER,q,killclient
bind=SUPER,Return,spawn,wezterm

bind=SUPER,r,reload_config

exec-once=zsh ~/.config/mango/autostart.sh

